export { default as Hero } from './Hero'
export { default as Menu } from './Menu'
export { default as About } from './About'
export { default as CatGrid } from './CatGrid'
export { default as AboutUs } from './AboutUs'
